# ==================================================
# Original Code
# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
# Modified by handbros(@kotran-io)
# ==================================================

# Project information
site_name: Kotran
site_url: https://kotran.io/
site_author: Kotran Contributors
site_description: Kotran is an open source neural machine translator.

# Repository
repo_name: kotran-io/kotran-website
repo_url: https://github.com/kotran-io/kotran-website
edit_uri: blob/main/docs/

# Copyright
copyright: >
  Copyright &copy; 2023 Kotran

# Configuration
theme:
  language: en
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.tracking
    # - search.highlight
    # - search.share
    # - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: white
      accent: indigo
  font:
    text: Inter
    code: Fira Code
  favicon: assets/symbol.svg
  logo: assets/signature.svg

# Plugins
plugins:
  # - search:
  #     separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

# Customization
extra:
  generator: false
  annotate:
    json: [.s2]
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - reject
      - manage
  social:
    - name: Home
      icon: fontawesome/solid/house
      link: https://kotran.io
    - name: Support
      icon: fontawesome/solid/envelope
      link: mailto:support@kotran.io
    - name: Feedback
      icon: fontawesome/solid/lightbulb
      link: https://kotran.io/support

# Extra CSS
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: kotran-io
      repo: kotran-website
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: 
    - index.md
  - Guides:
    - guides/index.md
    - User Guide: 
      - guides/user/index.md
      - Quickstart: guides/user/quickstart.md
      - Installation: guides/user/installation.md
      - Customization: guides/user/customization.md
      - Mode:
        - guides/user/mode/index.md
        - Text: guides/user/mode/text.md
        - Image: guides/user/mode/image.md
        - Audio: guides/user/mode/audio.md
        - Document: guides/user/mode/document.md
    - Developer Guide:
      - guides/developer/index.md
      - Concepts: guides/developer/concepts.md
      - Workflow: guides/developer/workflow.md
      - API: guides/developer/api.md
    - Changelog: guides/changelog.md
    - License: guides/license.md
  - Releases:
    - releases.md
  - Support:
    - support.md